"""make left_at nullable

Revision ID: 096d8072e51a
Revises: bb241558bd59
Create Date: 2025-09-19 22:17:26.723124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096d8072e51a'
down_revision: Union[str, None] = 'bb241558bd59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'last_read_message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'last_read_message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
