"""make last_read_message_id nullable

Revision ID: b77055eb4b1e
Revises: 5dbac2c3916b
Create Date: 2025-09-20 09:57:06.135983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b77055eb4b1e'
down_revision: Union[str, None] = '5dbac2c3916b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'reply_to_message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'reply_to_message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
