"""chnage tables

Revision ID: bc3fd524aef5
Revises: bc1de1c64c88
Create Date: 2025-09-22 17:15:47.160430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc3fd524aef5'
down_revision: Union[str, None] = 'bc1de1c64c88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
